[2024-05-25T04:43:33.927+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T04:43:33.940+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Customer_Prosensity_DAG.success manual__2024-05-25T04:43:22.435397+00:00 [queued]>
[2024-05-25T04:43:33.946+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Customer_Prosensity_DAG.success manual__2024-05-25T04:43:22.435397+00:00 [queued]>
[2024-05-25T04:43:33.946+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-25T04:43:33.953+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): success> on 2024-05-25 04:43:22.435397+00:00
[2024-05-25T04:43:33.959+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=86) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T04:43:33.960+0000] {standard_task_runner.py:63} INFO - Started process 88 to run task
[2024-05-25T04:43:33.960+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Customer_Prosensity_DAG', 'success', 'manual__2024-05-25T04:43:22.435397+00:00', '--job-id', '4424', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_customer_sqlite3.py', '--cfg-path', '/tmp/tmpgxqfbf3p']
[2024-05-25T04:43:33.961+0000] {standard_task_runner.py:91} INFO - Job 4424: Subtask success
[2024-05-25T04:43:33.991+0000] {task_command.py:426} INFO - Running <TaskInstance: Customer_Prosensity_DAG.success manual__2024-05-25T04:43:22.435397+00:00 [running]> on host cb453a136ab9
[2024-05-25T04:43:34.043+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NhơnVõ' AIRFLOW_CTX_DAG_ID='Customer_Prosensity_DAG' AIRFLOW_CTX_TASK_ID='success' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T04:43:22.435397+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-25T04:43:22.435397+00:00'
[2024-05-25T04:43:34.044+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T04:43:34.044+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-25T04:43:34.045+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "success data . . ."']
[2024-05-25T04:43:34.053+0000] {subprocess.py:86} INFO - Output:
[2024-05-25T04:43:34.054+0000] {subprocess.py:93} INFO - success data . . .
[2024-05-25T04:43:34.054+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-25T04:43:34.055+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T04:43:34.069+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Customer_Prosensity_DAG, task_id=success, run_id=manual__2024-05-25T04:43:22.435397+00:00, execution_date=20240525T044322, start_date=20240525T044333, end_date=20240525T044334
[2024-05-25T04:43:34.093+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-25T04:43:34.104+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T04:43:34.105+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
