[2024-05-23T08:43:55.149+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T08:43:55.171+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Customer_Prosensity_DAG.success manual__2024-05-23T08:43:41.223820+00:00 [queued]>
[2024-05-23T08:43:55.179+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Customer_Prosensity_DAG.success manual__2024-05-23T08:43:41.223820+00:00 [queued]>
[2024-05-23T08:43:55.180+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-23T08:43:55.193+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): success> on 2024-05-23 08:43:41.223820+00:00
[2024-05-23T08:43:55.201+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=327) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-23T08:43:55.202+0000] {standard_task_runner.py:63} INFO - Started process 329 to run task
[2024-05-23T08:43:55.202+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Customer_Prosensity_DAG', 'success', 'manual__2024-05-23T08:43:41.223820+00:00', '--job-id', '4416', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_customer_sqlite3.py', '--cfg-path', '/tmp/tmpc4pk5mef']
[2024-05-23T08:43:55.203+0000] {standard_task_runner.py:91} INFO - Job 4416: Subtask success
[2024-05-23T08:43:55.248+0000] {task_command.py:426} INFO - Running <TaskInstance: Customer_Prosensity_DAG.success manual__2024-05-23T08:43:41.223820+00:00 [running]> on host cb453a136ab9
[2024-05-23T08:43:55.316+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NhơnVõ' AIRFLOW_CTX_DAG_ID='Customer_Prosensity_DAG' AIRFLOW_CTX_TASK_ID='success' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T08:43:41.223820+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-23T08:43:41.223820+00:00'
[2024-05-23T08:43:55.317+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T08:43:55.318+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-23T08:43:55.318+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "success data . . ."']
[2024-05-23T08:43:55.332+0000] {subprocess.py:86} INFO - Output:
[2024-05-23T08:43:55.333+0000] {subprocess.py:93} INFO - success data . . .
[2024-05-23T08:43:55.334+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-23T08:43:55.334+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T08:43:55.352+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Customer_Prosensity_DAG, task_id=success, run_id=manual__2024-05-23T08:43:41.223820+00:00, execution_date=20240523T084341, start_date=20240523T084355, end_date=20240523T084355
[2024-05-23T08:43:55.376+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-23T08:43:55.390+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T08:43:55.391+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
